package pers.ash.shiro.mapper.draftaudit;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.ash.shiro.model.draftaudit.Attachment;
import pers.ash.shiro.model.draftaudit.AttachmentExample;

public interface AttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int countByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int deleteByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    List<Attachment> selectByExample(AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    Attachment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") Attachment record, @Param("example") AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByExample(@Param("record") Attachment record, @Param("example") AttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByPrimaryKeySelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_attachment
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByPrimaryKey(Attachment record);
}