package pers.ash.shiro.mapper.draftaudit;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.ash.shiro.model.draftaudit.AuditRecord;
import pers.ash.shiro.model.draftaudit.AuditRecordExample;

public interface AuditRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int countByExample(AuditRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int deleteByExample(AuditRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int insert(AuditRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int insertSelective(AuditRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    List<AuditRecord> selectByExample(AuditRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    AuditRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") AuditRecord record, @Param("example") AuditRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByExample(@Param("record") AuditRecord record, @Param("example") AuditRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByPrimaryKeySelective(AuditRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_audit_record
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByPrimaryKey(AuditRecord record);
}