package pers.ash.shiro.mapper.draftaudit;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.ash.shiro.model.draftaudit.Draft;
import pers.ash.shiro.model.draftaudit.DraftExample;

public interface DraftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int countByExample(DraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int deleteByExample(DraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int insert(Draft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int insertSelective(Draft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    List<Draft> selectByExampleWithBLOBs(DraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    List<Draft> selectByExample(DraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    Draft selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") Draft record, @Param("example") DraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") Draft record, @Param("example") DraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByExample(@Param("record") Draft record, @Param("example") DraftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByPrimaryKeySelective(Draft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Draft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro_draft
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    int updateByPrimaryKey(Draft record);
}