package pers.ash.shiro.model.draftaudit;

public class Attachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_attachment.id
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_attachment.name
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_attachment.draftId
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    private String draftId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_attachment.id
     *
     * @return the value of shiro_attachment.id
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_attachment.id
     *
     * @param id the value for shiro_attachment.id
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_attachment.name
     *
     * @return the value of shiro_attachment.name
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_attachment.name
     *
     * @param name the value for shiro_attachment.name
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_attachment.draftId
     *
     * @return the value of shiro_attachment.draftId
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public String getDraftId() {
        return draftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_attachment.draftId
     *
     * @param draftId the value for shiro_attachment.draftId
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public void setDraftId(String draftId) {
        this.draftId = draftId == null ? null : draftId.trim();
    }
}