package pers.ash.shiro.model.draftaudit;

import java.io.Serializable;

public class RawDraft implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1036984855608739680L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_raw_draft.id
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_raw_draft.draftId
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    private String draftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_raw_draft.title
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_raw_draft.remark
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_raw_draft.content
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_raw_draft.id
     *
     * @return the value of shiro_raw_draft.id
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_raw_draft.id
     *
     * @param id the value for shiro_raw_draft.id
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_raw_draft.draftId
     *
     * @return the value of shiro_raw_draft.draftId
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public String getDraftId() {
        return draftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_raw_draft.draftId
     *
     * @param draftId the value for shiro_raw_draft.draftId
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public void setDraftId(String draftId) {
        this.draftId = draftId == null ? null : draftId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_raw_draft.title
     *
     * @return the value of shiro_raw_draft.title
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_raw_draft.title
     *
     * @param title the value for shiro_raw_draft.title
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_raw_draft.remark
     *
     * @return the value of shiro_raw_draft.remark
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_raw_draft.remark
     *
     * @param remark the value for shiro_raw_draft.remark
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_raw_draft.content
     *
     * @return the value of shiro_raw_draft.content
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_raw_draft.content
     *
     * @param content the value for shiro_raw_draft.content
     *
     * @mbggenerated Wed Oct 21 09:28:44 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}