package pers.ash.shiro.model.draft;

public class Draft {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.id
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.title
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.number
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.authorId
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.auditorId
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String auditorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.remark
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.createDate
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.lastUpdateDate
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.currentState
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String currentState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.readTag
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private Integer readTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.auditorTotalCount
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private Integer auditorTotalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.auditorPassedCount
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private Integer auditorPassedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro_draft.content
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.id
     *
     * @return the value of shiro_draft.id
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.id
     *
     * @param id the value for shiro_draft.id
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.title
     *
     * @return the value of shiro_draft.title
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.title
     *
     * @param title the value for shiro_draft.title
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.number
     *
     * @return the value of shiro_draft.number
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.number
     *
     * @param number the value for shiro_draft.number
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.authorId
     *
     * @return the value of shiro_draft.authorId
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.authorId
     *
     * @param authorId the value for shiro_draft.authorId
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId == null ? null : authorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.auditorId
     *
     * @return the value of shiro_draft.auditorId
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.auditorId
     *
     * @param auditorId the value for shiro_draft.auditorId
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setAuditorId(String auditorId) {
        this.auditorId = auditorId == null ? null : auditorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.remark
     *
     * @return the value of shiro_draft.remark
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.remark
     *
     * @param remark the value for shiro_draft.remark
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.createDate
     *
     * @return the value of shiro_draft.createDate
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.createDate
     *
     * @param createDate the value for shiro_draft.createDate
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.lastUpdateDate
     *
     * @return the value of shiro_draft.lastUpdateDate
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.lastUpdateDate
     *
     * @param lastUpdateDate the value for shiro_draft.lastUpdateDate
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setLastUpdateDate(String lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate == null ? null : lastUpdateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.currentState
     *
     * @return the value of shiro_draft.currentState
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getCurrentState() {
        return currentState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.currentState
     *
     * @param currentState the value for shiro_draft.currentState
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setCurrentState(String currentState) {
        this.currentState = currentState == null ? null : currentState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.readTag
     *
     * @return the value of shiro_draft.readTag
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public Integer getReadTag() {
        return readTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.readTag
     *
     * @param readTag the value for shiro_draft.readTag
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setReadTag(Integer readTag) {
        this.readTag = readTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.auditorTotalCount
     *
     * @return the value of shiro_draft.auditorTotalCount
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public Integer getAuditorTotalCount() {
        return auditorTotalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.auditorTotalCount
     *
     * @param auditorTotalCount the value for shiro_draft.auditorTotalCount
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setAuditorTotalCount(Integer auditorTotalCount) {
        this.auditorTotalCount = auditorTotalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.auditorPassedCount
     *
     * @return the value of shiro_draft.auditorPassedCount
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public Integer getAuditorPassedCount() {
        return auditorPassedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.auditorPassedCount
     *
     * @param auditorPassedCount the value for shiro_draft.auditorPassedCount
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setAuditorPassedCount(Integer auditorPassedCount) {
        this.auditorPassedCount = auditorPassedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro_draft.content
     *
     * @return the value of shiro_draft.content
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro_draft.content
     *
     * @param content the value for shiro_draft.content
     *
     * @mbggenerated Mon Oct 19 13:33:47 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}